# fly -t lite set-pipeline -c pipeline/pipeline.yaml -p tests:phpunit

resources:
  - name: resource-concourse-php
    type: git
    source:
      uri: https://github.com/abinhho/concourse-php.git
      branch: master

jobs:
- name: test
  plan:
  - get: resource-concourse-php
    trigger: true
  - task: install
    file: resource-concourse-php/pipeline/build.yaml
  - task: test
    file: resource-concourse-php/pipeline/test.yaml
  - task: report
    file: resource-concourse-php/pipeline/report.yaml